// Load Testing Configuration for Supabase + Flutter E-Voting System

export const SUPABASE_URL = __ENV.SUPABASE_URL || 'https://xyczocswufelhpcrmjow.supabase.co';
export const SUPABASE_ANON_KEY = __ENV.SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5Y3pvY3N3dWZlbGhwY3Jtam93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyNzM4MzAsImV4cCI6MjA5NTg0OTgzMH0.ceteY6McC6WMg5Ku5ciKQTZsZXnKaM8bDo4qQObZDE8';

export const COMMON_HEADERS = {
  'apikey': SUPABASE_ANON_KEY,
  'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
  'Content-Type': 'application/json',
};

export function getAuthHeaders(jwtToken) {
  return {
    'apikey': SUPABASE_ANON_KEY,
    'Authorization': `Bearer ${jwtToken}`,
    'Content-Type': 'application/json',
  };
}

// Global Thresholds (Adjusted for cloud remote Supabase API latency)
export const THRESHOLDS = {
  'http_req_duration': ['p(95)<2000'], // 95% of requests must complete below 2000ms
  'http_req_failed': ['rate<0.05'],   // Error rate must be less than 5%
};

// Scenarios for 10, 50, 100, 500 VUs with Ramp-up and Ramp-down stages
export const SCENARIOS = {
  smoke_10: {
    executor: 'ramping-vus',
    startVUs: 1,
    stages: [
      { duration: '5s', target: 10 },
      { duration: '10s', target: 10 },
      { duration: '5s', target: 0 },
    ],
  },
  load_50: {
    executor: 'ramping-vus',
    startVUs: 5,
    stages: [
      { duration: '5s', target: 50 },
      { duration: '15s', target: 50 },
      { duration: '5s', target: 0 },
    ],
  },
  stress_100: {
    executor: 'ramping-vus',
    startVUs: 10,
    stages: [
      { duration: '5s', target: 100 },
      { duration: '15s', target: 100 },
      { duration: '5s', target: 0 },
    ],
  },
  soak_500: {
    executor: 'ramping-vus',
    startVUs: 20,
    stages: [
      { duration: '10s', target: 500 },
      { duration: '20s', target: 500 },
      { duration: '10s', target: 0 },
    ],
  },
};

export function generateHTMLReport(data, title) {
  const reqs = data.metrics.http_reqs ? data.metrics.http_reqs.values.count : 0;
  const reqsSec = data.metrics.http_reqs ? data.metrics.http_reqs.values.rate.toFixed(2) : 0;
  const durationP95 = data.metrics.http_req_duration ? data.metrics.http_req_duration.values['p(95)'].toFixed(2) : 0;
  const durationAvg = data.metrics.http_req_duration ? data.metrics.http_req_duration.values.avg.toFixed(2) : 0;
  const failRate = data.metrics.http_req_failed ? (data.metrics.http_req_failed.values.rate * 100).toFixed(2) : 0;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title} - k6 Load Test Report</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #0f172a; color: #f8fafc; margin: 0; padding: 24px; }
    .container { max-width: 900px; margin: 0 auto; background: #1e293b; border-radius: 12px; padding: 32px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }
    h1 { color: #38bdf8; font-size: 24px; border-bottom: 2px solid #334155; padding-bottom: 12px; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-top: 24px; }
    .card { background: #0f172a; padding: 20px; border-radius: 8px; border-left: 4px solid #38bdf8; }
    .card.success { border-left-color: #4ade80; }
    .card.danger { border-left-color: #f87171; }
    .label { font-size: 12px; text-transform: uppercase; color: #94a3b8; letter-spacing: 0.5px; }
    .value { font-size: 28px; font-weight: bold; margin-top: 8px; }
    .footer { margin-top: 32px; font-size: 12px; color: #64748b; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🚀 ${title} - k6 Execution Summary</h1>
    <div class="grid">
      <div class="card success">
        <div class="label">Total Requests</div>
        <div class="value">${reqs}</div>
      </div>
      <div class="card success">
        <div class="label">Requests / Sec</div>
        <div class="value">${reqsSec}</div>
      </div>
      <div class="card ${durationP95 < 2000 ? 'success' : 'danger'}">
        <div class="label">95th Percentile Latency</div>
        <div class="value">${durationP95} ms</div>
      </div>
      <div class="card success">
        <div class="label">Average Latency</div>
        <div class="value">${durationAvg} ms</div>
      </div>
      <div class="card ${failRate < 5 ? 'success' : 'danger'}">
        <div class="label">Error Rate</div>
        <div class="value">${failRate}%</div>
      </div>
    </div>
    <div class="footer">Generated by k6 Production Load Testing Engine • ${new Date().toISOString()}</div>
  </div>
</body>
</html>`;
}
